export enum CivType {
  Aztecs,
  Bengalis,
  Berbers,
  Bohemians,
  Britons,
  Bulgarians,
  Burgundians,
  Burmese,
  Byzantines,
  Celts,
  Chinese,
  Cumans,
  Dravidians,
  Ethiopians,
  Franks,
  Goths,
  Gujaras,
  Hindustanis,
  Huns,
  Incas,
  Italians,
  Japanese,
  Khmer,
  Koreans,
  Lithuanians,
  Magyars,
  Malay,
  Malians,
  Mayans,
  Mongols,
  Persians,
  Poles,
  Portuguese,
  Saracens,
  Sicilians,
  Slavs,
  Spanish,
  Tatars,
  Teutons,
  Turks,
  Vietnamese,
  Vikings,
}

export const CivTypeFormat: Map<CivType, string> = new Map([
  [CivType.Aztecs, "Aztecs"],
  [CivType.Bengalis, "Bengalis"],
  [CivType.Berbers, "Berbers"],
  [CivType.Bohemians, "Bohemians"],
  [CivType.Britons, "Britons"],
  [CivType.Bulgarians, "Bulgarians"],
  [CivType.Burgundians, "Burgundians"],
  [CivType.Burmese, "Burmese"],
  [CivType.Byzantines, "Byzantines"],
  [CivType.Celts, "Celts"],
  [CivType.Chinese, "Chinese"],
  [CivType.Cumans, "Cumans"],
  [CivType.Dravidians, "Dravidians"],
  [CivType.Ethiopians, "Ethiopians"],
  [CivType.Franks, "Franks"],
  [CivType.Goths, "Goths"],
  [CivType.Gujaras, "Gujaras"],
  [CivType.Hindustanis, "Hindustanis"],
  [CivType.Huns, "Huns"],
  [CivType.Incas, "Incas"],
  [CivType.Italians, "Italians"],
  [CivType.Japanese, "Japanese"],
  [CivType.Khmer, "Khmer"],
  [CivType.Koreans, "Koreans"],
  [CivType.Lithuanians, "Lithuanians"],
  [CivType.Magyars, "Magyars"],
  [CivType.Malay, "Malay"],
  [CivType.Malians, "Malians"],
  [CivType.Mayans, "Mayans"],
  [CivType.Mongols, "Mongols"],
  [CivType.Persians, "Persians"],
  [CivType.Poles, "Poles"],
  [CivType.Portuguese, "Portuguese"],
  [CivType.Saracens, "Saracens"],
  [CivType.Sicilians, "Sicilians"],
  [CivType.Slavs, "Slavs"],
  [CivType.Spanish, "Spanish"],
  [CivType.Tatars, "Tatars"],
  [CivType.Teutons, "Teutons"],
  [CivType.Turks, "Turks"],
  [CivType.Vietnamese, "Vietnamese"],
  [CivType.Vikings, "Vikings"],
]);
